#!/usr/bin/env node
/**
 * Convert documentMap.js from SharePoint URLs to local relative paths.
 * Uses the url-mapping.json generated by extract-urls.js.
 *
 * Usage: node scripts/convert-urls.js
 */

import { readFileSync, writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const docMapPath = join(__dirname, '../src/data/documentMap.js')
const mappingPath = join(__dirname, 'url-mapping.json')

const mapping = JSON.parse(readFileSync(mappingPath, 'utf-8'))
let src = readFileSync(docMapPath, 'utf-8')

// Add DOC_BASE_URL constant after the header comments
const headerEnd = src.indexOf('export const documentMap')
const header = src.slice(0, headerEnd)
const rest = src.slice(headerEnd)

const baseUrlBlock = `// Base URL for document hosting. Override via environment for Azure Blob, etc.
// Default: relative /docs/ path (served from public/docs/ by Vite)
const DOC_BASE_URL = '/docs'

`

// Replace each SharePoint URL with the local path
let converted = rest
let replacements = 0
for (const [sharepointUrl, localPath] of Object.entries(mapping)) {
  // URL-encode the local filename for safe use in URLs
  const parts = localPath.split('/')
  const folder = parts[0]
  const filename = parts.slice(1).join('/')
  const encodedFilename = encodeURIComponent(filename)
  const newUrl = '${DOC_BASE_URL}/' + folder + '/' + encodedFilename

  // Escape special regex chars in the sharepoint URL
  const escaped = sharepointUrl.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const regex = new RegExp(escaped, 'g')
  const before = converted
  converted = converted.replace(regex, newUrl)
  if (converted !== before) replacements++
}

// Change url values from single-quoted strings to template literals
// Match: url: '${DOC_BASE_URL}/...'  →  url: `${DOC_BASE_URL}/...`
converted = converted.replace(/url: '\$\{DOC_BASE_URL\}\/([^']+)'/g, 'url: `${DOC_BASE_URL}/$1`')

const output = header + baseUrlBlock + converted
writeFileSync(docMapPath, output)

console.log(`Converted ${replacements} unique URLs in documentMap.js`)
console.log(`Added DOC_BASE_URL constant`)
